[build]
  command = "node build.js"
  publish = "dist"

[[redirects]]
  from = "/emi-calculator/*"
  to = "/emi-calculator/:splat/index.html"
  status = 200

[[redirects]]
  from = "/sip-calculator/*"
  to = "/sip-calculator/:splat/index.html"
  status = 200

[[redirects]]
  from = "/car-loan/*"
  to = "/car-loan/:splat/index.html"
  status = 200